<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Add Tracking ID, Profile ID and Access Token to the main configuration file.' => 'Add Tracking ID, Profile ID and Access Token to the main configuration file.',
	'Administration' => 'إدارة',
	'Are you sure you want to delete this item?' => 'هل أنت متأكد من أنك تريد حذف هذا العنصر؟',
	'Avg. Time on Page' => 'Avg. Time on Page',
	'Avg. Visit Duration' => 'Avg. Visit Duration',
	'Bounce Rate' => 'Bounce Rate',
	'CSV' => 'CSV',
	'Changes saved.' => 'تم حفظ التغييرات',
	'Changes saved. You can add a new entry.' => 'تم حفظ التغييرات، يمكنك إضافة عنصر جديد',
	'Choose {name}' => 'اختر {name}',
	'Connect' => 'اتصال',
	'Connect with your Google Analytics account.' => 'ريط مع حساب غوغل للتحليل',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => 'لا يمكن إنشاء المجلد "{dir}". تأكد من أن المجلد "uploads" يمكن الكتابة عليه',
	'Could not create upload folder "{dir}".' => 'لا يمكن إنشاء المجلد "{dir}"',
	'Could not delete entry "{name}" with an ID "{pk}".' => 'لا يمكن إضافة العنصر "{name}" برقم الـID "{pk}"',
	'Could not load model "{name}".' => 'لا يمكن تحميل الموديل "{name}"',
	'Could not save file or file exists: "{file}".' => 'لا يمكن حفظ الملف "{file}"، أو هذا الملف موجود مسبقا',
	'Could not upload file.' => 'لا يمكن ترفيع الملف',
	'Create' => 'إضافة',
	'Create {name}' => 'إضافة {name}',
	'Delete' => 'حذف',
	'Desktop Pageviews' => 'Desktop Pageviews',
	'Device Traffic' => 'Device Traffic',
	'Direct {percentage}' => 'Direct {percentage}',
	'Download' => 'تحميل',
	'Download {name}' => 'تحميل {name}',
	'Edit {name}' => 'تعديل {name}',
	'Error' => 'خطأ',
	'Excel' => 'Excel',
	'Google Analytics setup' => 'Google Analytics setup',
	'Google Analytics summary for the past {days} days' => 'Google Analytics summary for the past {days} days',
	'Home' => 'الرئيسية',
	'Image' => 'صورة',
	'Image preview' => 'عرض الصورة',
	'Incorrect username or password.' => 'اسم المستخدم أو كلمة المرور غير صحيح',
	'Invalid file extension "{ext}".' => 'ملف غير صالح "{ext}".',
	'Keyword' => 'كلمة مفتاحية',
	'List' => 'عرض',
	'Login' => 'تسجيل الدخول',
	'Logout' => 'تسجيل الخروج',
	'MS CSV' => 'MS CSV',
	'Metric' => 'Metric',
	'New Visitors' => 'New Visitors',
	'New Visits' => 'New Visits',
	'Next' => 'التالي',
	'Overview' => 'مراجعة',
	'Page' => 'صفحة',
	'Pages / Visit' => 'Pages / Visit',
	'Pageviews' => 'Pageviews',
	'Password' => 'كلمة السر',
	'Paste authorization code here:' => 'Paste authorization code here:',
	'Please configure "username" and "password" properties of the module in configuration file.' => 'Please configure "username" and "password" properties of the module in configuration file.',
	'Please enter your username and password.' => 'يرجى إدخال كلمة اسم المستخدم و كلمة المرور.',
	'Preview' => 'عرض',
	'Referral {percentage}' => 'Referral {percentage}',
	'Referrer' => 'Referrer',
	'Reload page' => 'تحديث الصفحة',
	'Remember me next time' => 'تذكرني في المرة المقبلة',
	'Save' => 'حفظ',
	'Save and add another' => 'حفظ و إضافة عنصر آخر',
	'Save and continue editing' => 'حفظ و إكمال عملية التعديل',
	'Search {percentage}' => 'بحث {percentage}',
	'Select profile.' => 'اختيار الملف الشخصي',
	'Separate words with commas.' => 'فصل الكلمات بفاصلة',
	'Smartphone Pageviews' => 'Smartphone Pageviews',
	'Statistics' => 'إحصائيات',
	'Step {num}' => 'خطوة {num}',
	'Tablet Pageviews' => 'Tablet Pageviews',
	'There was an Google Analytics API service error {code}: {message}' => 'There was an Google Analytics API service error {code}: {message}',
	'Top Keywords' => 'Top Keywords',
	'Top Pages' => 'Top Pages',
	'Top Referrers' => 'Top Referrers',
	'Traffic Sources' => 'Traffic Sources',
	'Unable to authenticate with Auth code {code}: {message}' => 'Unable to authenticate with Auth code {code}: {message}',
	'Unique Pageviews' => 'Unique Pageviews',
	'Unique Visitors' => 'Unique Visitors',
	'Username' => 'اسم المستخدم',
	'Value' => 'القيمة',
	'Visits' => 'الزيارات',
);